[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Fuzz testing configuration
[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x1'

# Invariant testing configuration
[invariant]
runs = 256
depth = 128
fail_on_revert = false
call_override = false

# Strict profile for failOnRevert tests
[profile.strict]
fuzz = { runs = 256 }
invariant = { runs = 128, depth = 64, fail_on_revert = true }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
